### ISSUE TITLE
No article is being recognised on (many) issues last page

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-text-acquisition#24] opened 2018-11-19 10:33 UTC
Hi @mromanello we have issues with the last page of quite a lot of newpsaper issues

the iiif page does exist:
https://api-impresso.uni.lu/proxy/iiif/GDL-1902-05-12-a-p0004/full/500,/0/default.jpg

the solr doesn't show any articles on the page
https://dhlabsrv18.epfl.ch/solr/impresso_dev/select?q=page_id_ss:GDL-1902-05-12-a-p0004&rows=10

This is not related to GDL only, but also to JGD:
https://api-impresso.uni.lu/proxy/iiif/JDG-1996-03-02-a-p0038/full/500,/0/default.jpg

@tvanbeek

**Comment by mromanello** [comment] 2019-09-30 07:46
I've verified this in the current interface + current data (ISR) for the examples provided by @danieleguido , and am happy to report that the issue is fixed now (most certainly thanks to one of the bugfixes to the `text-importer` module).

**Closed by mromanello** 2019-09-30 07:46 UTC
Labels: bug, data
