### ISSUE TITLE
Improvement in sequence of logical articles

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-text-acquisition#74] opened 2020-01-20 10:04 UTC
The sequence of articles from the original data might not play very well with the front-end idea of presenting the articles in some order. E.g. masthead comes last on the page. One might be able to reorder the articles according to their coordinates.

https://impresso-project.ch/app/issue/JDG-1832-07-07-a/page/JDG-1832-07-07-a-p0001/article/JDG-1832-07-07-a-i0007?tab=toc
![image](https://user-images.githubusercontent.com/3041168/72717508-6978f000-3b74-11ea-850e-e80a739dc30f.png)

**Comment by simon-clematide** [comment] 2020-01-22 09:40
Also here we have quite an unnatural reading order. Is there anything edoardo could do about that? Or would we break all our content item ids... probably....

https://dev.impresso-project.ch/app/issue/luxland-1954-06-18-a/page/luxland-1954-06-18-a-p0003/article/luxland-1954-06-18-a-i0003?tab=toc

**Comment by simon-clematide** [comment] 2023-11-11 12:57
@piconti   @danieleguido  This needs further investigations while we are revising the text importer. 
The sequence of "logical" articles follows the somewhat arbitrary ALTO ids. This leads to a situation as in the link below, where the 1. article in the issue in the table of content is followed by an ad on page 3. When you use the Table of Contents in the left column to move down, it jumps from page 1 to page 3 and back instead of following a more or less natural reading sequence. Total user confusion is the result if one uses the TOC for navigating. 

@danieleguido  we should specify which information is used by the frontend for computing the TOC element order. I assume the physical sequence of the content items in the issue, but I might be wrong. Could you confirm? 
A simple fix could be at least order the TOC by start page of an article. A more fine-grained simple solution would be to reordert them by the top-left corner position of the first paragraph:  ct1 < ct2 if y(ct1.p1), x(ct1-p1) < y(ct2.p2), x(ct2.p2)  (main sorting criterion the y axis, second the x axis)

Url of example page: https://impresso-project.ch/app/issue/NZG-1881-10-01-a/view?sq=CgIYAgoSEAIYByABKgpBYmVudGN1cmVyCiYQAhgHIAEqHkxpZWJsaW5nc2ZhY2ggYWxsZXIgQWJlbnRjdXJlcg%3D%3D&p=1&articleId=i0030

<img width="1325" alt="image" src="https://github.com/impresso/impresso-text-acquisition/assets/3041168/80450301-aac6-49d9-a992-0e6bd932dfb1">

**Comment by piconti** [comment] 2023-11-13 15:09
Thank you for higlighting this and reviving this issue. 
It's true that this makes navigation using the ToC quite confusing. 

I had a quick look on the interface for a few titles from different importers, and thisordering issue seems to concern at least RERO 2 & 3 and BNL data. Olive data doesn't seem to have this issue, TETML and SWA use pages.

For the case of RERO 2 factors seem to play together:
- In the code, the page's "contents" are sorted based on their ID but as strings, which means for eg. a content with ID `DIVL10` is sorted before another with ID `DIVL9`. 
- The OCR content IDs also seem to be alphabetically ordered by type (Ads coming before Articles), and the types attributed to a content are not always correct. 
  - For the `NZG-1881-10-01-a` example above, the first contents are advertisements on page 4, followed by the various articles with the pages sorted, but with some ads wrongly labeled as articles (here in particular the example of ad on page 3). 

For BNL data, the same sorting alphabetical sorting of ids is present, but in addition some content-items are reconstructed and merged during the parsing which might also affect the numbering.

Hence some approaches could each fix parts of the issue:
- Only taking into consideration the content ID's litteral value when sorting -> may sort ads before the rest
- Considering articles before other types of content -> if ads or other types of content are scattered throughout the issue, the same jumping from page to page could take place
- Fetching the page number and processing page per page -> could work but would probably cause issues of complexify the sorting when contents span over two pages. 

The sorting should be reproducible easily at different stages of the parsing, and ideally not be too complex to reduce the possibility for errors due to edge cases. Using coordinates could also work but given they are not always correct, and are stored on the alto files (instead of the mets) it seems like it would be too complex for our needs here. 

I can modify the code to fix this, but this would mean substantial recomputation for all RERO and BNL data, and loss of continuity with the CI ids (old links would not map to the same articles etc). 
I don't know to which extent this change could cause downstream issues (@e-maud and @danieleguido have a better idea for this). Depending on this, directly correcting this in the ToC display may be simpler.

In any case, I correct this issue for not-yet-ingested Mets/Alto collections.

**Comment by e-maud** [comment] 2023-11-13 16:35
Many thanks for spotting Simon and Pauline for checking the details.

**With respect to breaking or not IDs in general**     
The "permanency" of content item ids is a recurring issue we are confronted with, each time asking ourselves whether we go for it or not. Risks are 1) broken links of ppl working with the data, externally or with collections in the interface, and 2) our data getting disrupted internally, with the need to re-do the entire processing on new ids (small scale fixes are possible, but not big).

Since we are starting a new project, I would be tempted to say that's a good moment for an id reset if there is a need.
In case of change of ids, the primary issues at hand are:
- the continuity/consistency of user collections, which could be resolved via a flat but giant and certainly not 100% reliable mapping (e.g. keeping a list of old and new ids when generating new canonical data).
- the correspondance between content items and annotations that include ci id information: NE, topics, TR

**With respect to the TOC problem**
- in general, I think we should aim at fixing the data rather than fixing the interface on top of "imperfect" data;
- that being said, we have data of different 'stages':
	- new data: new importers will take into account the (somehow) reading order;
	- Swiss old data: all titles but GDL and JDG will be renewed with new OLR, and will likely have new article segmentation, thus generating new ids. Time-wise not before 2026 I'd say. But it might not be worth re-generating ids if they will change again 'soon' (?)
	- new NZZ data will arrive soon and be re-ingested (with new ids). Here not sure if user collection mapping is necessary, since it goes from page to article level. New enrichment will be necessary.
	- old BNL data will have updated OCR but same OLR and, among the present collections, is likely to be the only one with old TOC-order-incompatible ids. The question thus being whether we want to carry over those wrongly ordered ids. The front-end fix seems an easy one here, but I am wondering if in the future we will rely on the ordering for something else, and regret this absence of fix at data level.
- Before fixes are done (if decided), the TOC could meanwhile be sorted by page number.

**Background**
- We agree that CI are numbered at issue level according to an logic not related to reading and page order (e.g. #1 could be on the last page), that they can be grouped by page, but that within a page there is no order. (?)
- title/issues /page/ci relations are stored in MySQl and I think Daniele takes this info from there.

**Comment by simon-clematide** [comment] 2023-11-13 17:02
Changing issue IDs is always a pain. I agree. I think adding a reading order could be a compromise.

**Comment by piconti** [comment] 2024-01-10 10:37
A [google sheet document](https://docs.google.com/spreadsheets/d/1m-EaqsYpclDuUzE4vcl2DRgyrPQ6aauoMUAwpthx8Y4/edit#gid=0) was created summarizing all problems that are currently in the data, including regarding this issue, as well as the fixing approach for each.

It was decided that a `reading_order` property would be added to the CI metadata (under `i['m']['reading_order']`) when necessary – meaning when the current CI Id ordering would not follow a page-to-page logic. 
The `reading_order` would thus make sure that all CIs on the same page are displayed one after the other in the ToC.

Since issue #117 also requires some modifications to the data, the reading order will also directly be added to the issue canonical data in case of reingestion (all reingested journals also present this issue). 
Otherwise, it will only be added by patching when necessary.

- [ ] **BNL**: Reingestion to correct the various issues.
- [ ] **BNF**: Reingestion to correct the various issues.
- [ ] **BNF-EN**: Reingestion to correct the various issues.
- [ ] **RERO 2&3*3: Patch at the issue-level to add the `reading_order` property.

**Comment by piconti** [comment] 2024-01-11 08:31
Additional note: 
Since the reading order will then be ingested in Solr, it should also be present in the rebuilt. 
As a result, the rebuilt data should also be patched for journals for which the canonical data is patched (here RERO 2&3). 
Additionally, the code of the rebuilt should be modified to include this property.

**Closed** 2024-05-01 09:17 UTC
Labels: bug, data
